name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ "master", "main" ] 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm install

      - name: Build app
        run: npm run build -- --base-href=/${{ github.event.repository.name }}/

      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Detecta la carpeta de salida y crea 404.html para SPA
      - name: Prepare artifact
        id: prep
        run: |
          set -e
          OUT=$(ls -d dist/*/browser dist/* 2>/dev/null | head -n 1)
          echo "DIST=$OUT" >> $GITHUB_OUTPUT
          cp "$OUT/index.html" "$OUT/404.html"
          echo "Using dist path: $OUT"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.prep.outputs.DIST }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

        id: deployment
        uses: actions/deploy-pages@v4
